#!/bin/bash

# ping_flood $HOST
HOST=$1

# Cortisol test
# output format: primary metric, comments

# rtt min/avg/max/mdev = 0.036/0.050/21.354/0.215 ms, pipe 2, ipg/ewma 0.057/0.050 ms
output=$(sudo ping -f -s 64 -c 50000 -q $HOST)

echo  $output | sed -nr 's,.* ([0-9]+\.[0-9]+)/([0-9]+\.[0-9]+)/([0-9]+\.[0-9]+)/([0-9]+\.[0-9]+).*,\2,p'
echo  $output | sed -r '/^rtt/p'

